### ISSUE TITLE
Class autocompletion doesn't work without 'use' keyword

### ISSUE THREAD

**Issue by golaod** [mkusher/padawan.php#59]
That's something what is missing I think. When I have class like App\Entities\Order and I just type Order, I don't get anything unless I type 'use' keyword before. It wouldn't be a problem if I could do 'find use' and it would automatically add it to other use lines and leave 'Order' in current line. Is there a chance to enable that autocompletion without use keyword at least?

**Comment by mkusher** [comment]
@golaod can you provide more examples?

**Comment by golaod** [comment]
Sure.

Let's say I have `App\Entities\ConnectorFailedJob`

and then somewhere in the code I type

```
namespace App\Console\Commands;

class MyCommand
{
    public function run()
    {
        ConnectorF // I expect to get hint with App\Entities\ConnectorFailedJob, but I don't get it

        // although I can get it when typing
        use ConnectorF // here it works, but of course it's pointless

        // because I will get
        use App\Entities\ConnectorFailedJob;
    }
}
```

Of course again it wouldn't be a problem if, for istance, 'find use' command would automatically change that line to:

```
namespace App\Console\Commands;

use App\Entities\ConnectorFailedJob;

class MyCommand
{
    public function run()
    {
        ConnectorFailedJob
        // or even better, that I don't have to type 'use' in the middle of the code
        // because would be great to have autocompletion of classes and FQCN anywhere
    }
}
```

**Comment by mkusher** [comment]
@golaod are you using master version?

**Comment by mkusher** [comment]
so, understood. 
~~The fix could be quite easy: we just need to add classes to this map https://github.com/mkusher/padawan.php/blob/master/src/Padawan/Domain/Completer/GlobalFunctionsCompleter.p~~
Fix is really simple:  [this context](https://github.com/mkusher/padawan.php/blob/master/src/Padawan/Domain/Completer/GlobalFunctionsCompleter.php#L52) should be added to [class name completer canHandle](https://github.com/mkusher/padawan.php/blob/master/src/Padawan/Domain/Completer/ClassNameCompleter.php#L30)

**Comment by golaod** [comment]
Thanks for the info, but I can't use master version.

```
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Can only install one of: react/http[dev-master, v0.4.1].
    - Can only install one of: react/http[v0.4.1, dev-master].
    - Can only install one of: react/http[dev-master, v0.4.1].
    - don't install react/http dev-master|don't install react/react v0.4.1
    - mkusher/padawan dev-master requires react/http dev-master -> satisfiable by react/http[dev-master].
    - Installation request for mkusher/padawan master -> satisfiable by mkusher/padawan[dev-master].
    - Installation request for react/http (locked at v0.4.1) -> satisfiable by react/http[v0.4.1], react/react[v0.4.1].
```

**Comment by golaod** [comment]
Any suggestions?

**Comment by mkusher** [comment]
@golaod why do you need global react/http v0.4.1?

**Comment by golaod** [comment]
I don't need it. I just install your package with `composer global require mkusher/padawan:master`

**Comment by mkusher** [comment]
@golaod can you remove it completely and then install again?
`$ composer global require mkusher/padawan:dev-master`

**Comment by golaod** [comment]
```
~/.composer$ composer global require mkusher/padawan:dev-master
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Can only install one of: react/http[dev-master, v0.4.1].
    - Can only install one of: react/http[v0.4.1, dev-master].
    - Can only install one of: react/http[dev-master, v0.4.1].
    - mkusher/padawan dev-master requires react/http dev-master -> satisfiable by react/http[dev-master].
    - Installation request for mkusher/padawan dev-master -> satisfiable by mkusher/padawan[dev-master].
    - Installation request for react/http (locked at v0.4.1) -> satisfiable by react/http[v0.4.1].


Installation failed, reverting ./composer.json to its original content.
```

**Comment by mkusher** [comment]
@golaod can you show your global composer.json?

**Comment by golaod** [comment]
```
cat composer.json 
{
    "require": {
        "mkusher/padawan-di": "^0.1.1",
        "pbogut/padawan-magento": "dev-master"
    },
    "minimum-stability": "dev"
}
```

**Comment by mkusher** [comment]
@golaod please, try following:

``` bash
$ composer global remove react/react
$ composer global require mkusher/padawan:dev-master
```

**Comment by golaod** [comment]
Thank you very much, that one helped. Now let me check, whether namespaces work in the middle of code.

**Comment by golaod** [comment]
Nope, still doesn't autocomplete.

**Comment by mkusher** [comment]
@golaod now only global functions will work, in order to complete fqcn we need to add [this fix](https://github.com/mkusher/padawan.php/issues/59#issuecomment-245586948) to the completer

**Comment by golaod** [comment]
I added it manually to your code, but right now with dev-master even use statement at the top of the file doesn't populate popup with classes

**Comment by golaod** [comment]
And if you wanna ask whether padawan-server is working. It does, because doing $this-> inside a method  populates the popup.

**Comment by golaod** [comment]
Hm...during further tests I found out that $this-> is not populated by your module, but by sublime. In that case padawan stopped working at all :(

**Comment by mkusher** [comment]
@golaod run `padawan generate` from the root dir of your project.
I've also sent https://github.com/mkusher/padawan.php/pull/64

**Comment by golaod** [comment]
I run padawan generate, I did the same in sublime, but it still doesn't autocomplete classes at the top of the file when writing along with 'use' keyword, doesn't autocomplete inherited methods on $this->, and #64 has a bug

**Comment by mkusher** [comment]
@golaod yeah, I see the bug. So, I should spend more time on it :(
Have you restarted padawan server after you ran generate?

**Comment by golaod** [comment]
Yes I did and same thing as with padawan generate. Doesn't matter if I run it from the console or sublime.

**Comment by mkusher** [comment]
ooh, that's strange. Can you debug it with nc(show me request/response)?

**Comment by golaod** [comment]
Any suggestion on how to debug it?

**Comment by golaod** [comment]
Nvm, I figured out to catch the request first and then send it over

**Comment by golaod** [comment]
Request sent by sublime

```
POST /complete?path=%2Fhome%2Fgolaod%2Fwww%2Fproject&column=16&line=36&filepath=%2Fmodules%2FOrder%2FEntities%2FOrderItem.php HTTP/1.1
Accept-Encoding: identity
Host: 127.0.0.1:15155
Content-Length: 971
Content-Type: application/x-www-form-urlencoded
User-Agent: Python-urllib/3.3
Connection: close

<?php
namespace Modules\Order\Entities;

use App\Connectors\Traits\ConnectorModelColumns;
use App\Entities\Product;
use App\Traits\ModelHelpers;
use Illuminate\Database\Eloquent\Model;

class OrderItem extends Model
{
    use ModelHelpers, ConnectorModelColumns;

    protected $fillable = [
        'order_id', 'product_sku', 'qty', 'connector_id', 'external_id', 'external_data',
    ];

    protected $casts = [
        'order_id'   => 'int',
        'qty'        => 'int',
        'connector_id'  => 'int',
        'external_data' => 'array',
    ];

    public function __toString()
    {
        return $this->name;
    }

    public function order()
    {
        return $this->hasOne(Order::class, 'id', 'order_id');
    }

    public function product()
    {
        $this->
        return $this->hasOne(Product::class, 'sku', 'product_sku');
    }

    public function getNameAttribute()
    {
        return $this->product ? $this->product->name : '';
    }
}
```

As I couldn't use it to send it over to padawan-server through nc, so I built curl request

```
curl -XPOST -d '<?php
namespace Modules\Order\Entities;

use App\Connectors\Traits\ConnectorModelColumns;
use App\Entities\Product;
use App\Traits\ModelHelpers;
use Illuminate\Database\Eloquent\Model;

class OrderItem extends Model
{
    use ModelHelpers, ConnectorModelColumns;

    protected $fillable = [
        'order_id', 'product_sku', 'qty', 'connector_id', 'external_id', 'external_data',
    ];

    protected $casts = [
        'order_id'   => 'int',
        'qty'        => 'int',
        'connector_id'  => 'int',
        'external_data' => 'array',
    ];

    public function __toString()
    {
        return $this->name;
    }

    public function order()
    {
        return $this->hasOne(Order::class, 'id', 'order_id');
    }

    public function product()
    {
        $this->
        return $this->hasOne(Product::class, 'sku', 'product_sku');
    }

    public function getNameAttribute()
    {
        return $this->product ? $this->product->name : '';
    }
}' '127.0.0.1:15155/complete?path=%2Fhome%2Fgolaod%2Fwww%2Fproject&column=16&line=36&filepath=%2Fmodules%2FOrder%2FEntities%2FOrderItem.php'
```

It gets me response

```
{"completion":[],"context":[]}
```

And padawan server throws an error

```
[2016-09-09 14:34:19] completer.ERROR: exception 'PhpParser\Error' with message 'Syntax error, unexpected ',', expecting '(' on line 21'
```

**Comment by mkusher** [comment]
@golaod thx, will try to debug it later

**Comment by mkusher** [comment]
@golaod yeah, I've found the problem - wrong content-type header. I've already fixed it in https://github.com/mkusher/padawan.sublime/commit/46152ec32a82da57526f9cb77921a610b6b42071
so can you update your padawan plugin for sublime(maybe I have to make new tag\release?)?

**Comment by golaod** [comment]
Thanks for fixing the header as I was able to use nc to send request.

```
nc 127.0.0.1 15155 < request.log 
HTTP/1.1 200 OK
X-Powered-By: React/alpha
Content-Type: application/json
Transfer-Encoding: chunked

1e
{"completion":[],"context":[]}
0

```

Now what I found:
- Generate index stopped working. I removed index completely and tried to generate it. Progress bar just goes very fast and nothing happens. When I call `padawan generate` from console then it works ok. After generation when I try again in sublime, progress bar is still lightning fast.
- Autocompletion of anything still doesn't work.

Sorry to tell, but previous version, even though with missing features, was more stable :(

**Comment by golaod** [comment]
Please don't get me wrong with my last sentence, I was just referring to it, because I wanted to help with few missing features, but now if package doesn't work at all, it's just harder than I thought. I really appreciate your help and didn't want to judge your volunteer work

**Comment by mkusher** [comment]
> Sorry to tell, but previous version, even though with missing features, was more stable

yeah, that's why I haven't created new tag. 0.2 branch is quite stable and dev-master is development. Even with auto tests there are a lot of untested cases.
I tried completion in your file without an index and got completion for current file context(using dev-master both for sublime plugin and padawan). Not sure how to reproduce your situation :(

**Comment by golaod** [comment]
I also get completion for current file, but I think it should return more, like for instance inherited methods. Plus it still doesn't return completion for fqcns

**Comment by mkusher** [comment]
@golaod so does it return completions or it returns nothing?

**Comment by golaod** [comment]
it doesn't return completions from padawan. In case

```
class A
{
    public function test() {}
}

class B extends A
{
    public function __construct()
    {
        $this->
    }

    public function debug() {}
}
```

I see only 'debug' whereas should also see 'test' method

**Comment by mkusher** [comment]
@golaod just created new file and tried your case and it works. So something wrong with padawan install. Maybe you're using some virtualization or something? I mean maybe padawan couldn't find files or something like?
And can you start `padawan-server` from your terminal and copy it's output here for this case?

**Comment by golaod** [comment]
Exactly, because you pasted both classes into the same file. I gave you a simple case, but of course I was referring to a regular day scenario, where your classes extend other classes (from other files).

**Comment by mkusher** [comment]
@golaod oh, I just need to understand what's wrong. 

``` php
<?php
class A
{
    public function test() {}
    protected function test2() {}
    private function test3() {}
}

class B extends A
{
    public function __construct()
    {
        $this->
    }

    public function debug() {}
}
```

in this case you should get `test`, `test2` and `debug`. So that will show whether padawan works at all or not

**Comment by golaod** [comment]
But as I wrote in my last comment: Everything depends on where you put those classes. If you have them both in the same class, then actually I don't need padawan to see test, test2 and debug, because sublime can handle it. Problem is when you put class A to file a.php and class B to file b.php, because padawan doesn't return methods from class A even though B extends A

**Comment by mkusher** [comment]
@golaod sublime couldn't understand private\protected and etc. And I need to understand what's wrong
